# Generated by Django 3.2.3 on 2021-05-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_table',
            old_name='customer',
            new_name='customervalue',
        ),
    ]
