# Generated by Django 3.2.3 on 2021-05-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_customer_book_table_customervalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='customervalue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_profile'),
        ),
    ]
