# Generated by Django 3.2.3 on 2021-05-19 20:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_book_table_customervalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownUserBookTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('people', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
