# Generated by Django 3.0.5 on 2021-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210512_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=35)),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('totol_hour', models.IntegerField()),
            ],
        ),
    ]
