# Generated by Django 3.2.3 on 2021-05-19 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_auto_20210519_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='user',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
