# Generated by Django 3.1 on 2020-10-17 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('report', '0002_auto_20201018_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavehr',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
