# Generated by Django 3.0.7 on 2020-10-18 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20201018_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydrcallreport',
            name='dr_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.DrMasterList'),
        ),
        migrations.DeleteModel(
            name='MonthlyplanList',
        ),
    ]
